name: Docker Web API Build

on:
  push:
    paths:
      - 'src/dotnet/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ dev, main ]
    paths:
      - 'src/dotnet/**'
      - '.github/workflows/**'

env:
  DOCKERFILE_PATH: "CarbonAware.WebApi/Dockerfile"
  HEALTH_ENDPOINT: "0.0.0.0:8080/emissions/bylocation?location=eastus"
  #Health Check Endpoint to be added as another story and replaced here

jobs:
  container-unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Docker Target Build
      run: docker build --target=build . -f ${DOCKERFILE_PATH} -t ca-api-build
      working-directory: ./src/dotnet

    - name: Docker Unit Test
      run: docker run -w //src/ ca-api-build dotnet test
      working-directory: ./src/dotnet

  container-validation:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Docker Target Final
        run: docker build . -f ${DOCKERFILE_PATH} -t ca-api
        working-directory: ./src/dotnet
        
      - name: Docker Run Container
        run: |
          docker run -d --name runnable-container -p 8080:80 ca-api
          docker container ls

      - name: Docker WGET Health Endpoint
        run: |
          wget -t 5 --waitretry=5 ${HEALTH_ENDPOINT}
