name: Docker Web API Build

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]
    paths:
      - 'src/**'
      - '.github/workflows/**'

env:
  DOCKERFILE_PATH: "CarbonAware.WebApi/src/Dockerfile"
  HEALTH_ENDPOINT: "0.0.0.0:8080/health"
  DATA_ENDPOINT: "0.0.0.0:8080/emissions/bylocation?location=eastus"
  DOTNET_SRC_DIR: "./src"

jobs:
  container-dotnet-build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          include-prerelease: false
      - name: Install dependencies
        run: dotnet restore
        working-directory: ${{ env.DOTNET_SRC_DIR }}
      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ${{ env.DOTNET_SRC_DIR }}
      - name: Test + Code Coverage
        run: dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
        working-directory: ${{ env.DOTNET_SRC_DIR }}
      - name: Codecov
        uses: codecov/codecov-action@v1

  container-validation:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Docker Target Final
        run: docker build . -f ${DOCKERFILE_PATH} -t ca-api
        working-directory: ./src
        
      - name: Docker Run Container
        run: |
          docker run -d --name runnable-container -p 8080:80 ca-api
          docker container ls

      - name: Docker WGET Health Endpoint
        run: |
          wget -t 5 --waitretry=5 ${HEALTH_ENDPOINT}

      - name: Docker WGET Data Endpoint
        run: |
          wget -t 5 --waitretry=5 ${DATA_ENDPOINT}

